# Generated by Django 4.1.7 on 2023-03-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_players_jersey_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='time_games',
            field=models.IntegerField(choices=[(5, '5'), (10, '10'), (20, '20')], default=5),
        ),
        migrations.AlterField(
            model_name='games',
            name='status',
            field=models.IntegerField(choices=[(0, 'TBD'), (1, 'Ongoing'), (2, 'Completed')], default=0),
        ),
    ]
